update candidate merge
mifort-org/hr-automation-ui pull request #28
Opened 2022-12-08 02:33 UTC by SharP3n

2022-12-09 06:11 UTC, NikaTikhonovets commented on src/app/pages/merge-page/merge-candidate/merge-candidate.component.scss
> +      // ::ng-deep .mat-checkbox-frame {
I think that in this case we need to add general style for checkboxes in the src/styles/custom-material.scss file for material components

2022-12-09 06:11 UTC, NikaTikhonovets commented on src/app/components/shared/avatar/avatar.component.ts
> -  @Input() candidate: Candidate | undefined | null;
awesome

2022-12-15 07:19 UTC, NikaTikhonovets requested changes

2022-12-15 07:19 UTC, NikaTikhonovets commented on src/app/pages/candidate-detail/candidate-communications/communication-comment/communication-comment.component.html
> +      [status]="(candidate |async)?.status"
I think for this case will be better get candidate once as ((candidate | async) as currentCandidate) and then use currentCandidate without pipe 'async'

2022-12-15 07:19 UTC, NikaTikhonovets commented on src/app/pages/merge-page/merge-candidate/merge-candidate.component.html
> +  [firstName]="candidate.fullName.split(' ')[0]"
better use getter from ts file for firstName and lastName

2022-12-20 18:06 UTC, RatiAbulashvil1 commented on src/app/pages/merge-page/merge-candidate/merge-candidate.component.html
> +  [firstName]="candidate.fullName.split(' ')[0]"
the candidate value which is inputted in this component is different from its type, should I make a refactor according to it? this would also allow us to use candidate.firstname & candidate.lastName on lines 14 & 15

2023-01-02 16:17 UTC, NikaTikhonovets approved these changes

2023-01-02 16:18 UTC, merged