fix layout candidates and candidate-detail pages
mifort-org/hr-automation-ui pull request #3
Opened 2022-09-08 14:24 UTC by antonlat

2022-09-09 14:10 UTC, NikaTikhonovets requested changes

2022-09-09 14:10 UTC, NikaTikhonovets commented on src/app/pages/candidates/candidates.component.scss
> +.mat-badge-content {
this is a duplicated style. You use it in three places

2022-09-12 10:29 UTC, antonlat commented on src/app/pages/candidates/candidates.component.scss
> +.mat-badge-content {
https://github.com/mifort-org/hr-automation-ui/pull/3/commits/a4630534ad1044e5a5e722be454b53f2a5001aae
remove unnecessarily style, in 2 another places use different styles for mat-badge-content

2022-09-12 11:14 UTC, NikaTikhonovets approved these changes

2022-09-12 11:14 UTC, merged